### ISSUE TITLE
redundant functionality should be either merged into existing features or existing updated

### ISSUE THREAD

**Issue by Geof23** [Geof23/QFP#11]
Should have caught this at merge time

reinterpret_float_as_int adds redundant mechanisms, please address

commit cdd1d623cb1f9d5466d7a8a916b01d7bd6edd739

**Comment by mikebentley15** [comment]
Okay, thanks.  I'll take a look.  Sorry about that!

**Comment by Geof23** [comment]
No worries!

**Comment by mikebentley15** [comment]
Next time I'll merge all pull requests myself into my local rel_lt.  I
didn't test them working together.  Good find!

**Comment by Geof23** [comment]
>
> Next time I'll merge all pull requests myself into my local rel_lt.


Good idea!


> I didn't test them working together. Good find!


Thanks Mike

>
>

**Comment by mikebentley15** [comment]
Addressed by [pull request #12](https://github.com/Geof23/QFP/pull/12)

**Comment by Geof23** [comment]
verified Makefile2 -- thanks
